### ISSUE TITLE
Support or block key ranges?

### ISSUE THREAD

**Issue by inexorabletash** [domenic/async-local-storage#11]
If the key space is not explicitly restricted (https://github.com/domenic/async-local-storage/issues/2) then as written some of the methods would implicitly support key ranges, e.g.

```js
area.get(IDBKeyRange.bounds(100,199));`
area.has(IDBKeyRange.bounds(1e6,1e7-1));`
area.delete(IDBKeyRange.lower(20));
```
And similarly, as written keys(), values() and entries() would not support ranges (unlike cursors/getAll()) thus limiting the functionality.

IMHO, either key ranges should be explicitly supported everywhere, or explicitly blocked.

**Comment by domenic** [comment]
Great find, thanks. I think we should explicitly block ranges everywhere, as it's encroaching on IDB's territory and too much of an abstraction leak (although the API is intentionally somewhat leaky; cf. `backingStore`).

Still unsure on how to resolve #2 though.

**Comment by domenic** [comment]
That makes sense!

**Comment by inexorabletash** [comment]
On the IDB spec side, "valid key" is used in prose but not well defined, it falls out of the [convert a value to a key](https://w3c.github.io/IndexedDB/#convert-a-value-to-a-key) algorithm.

On the JS side, you can use `indexedDB.cmp(potential_key, 0);` which will throw if a non-key is passed.

Note that using this will end up touching getters on the value twice (once when calling `cmp()`, once when calling `get()`), but I can't think of an alternative at the moment.

**Comment by domenic** [comment]
I think we can just do all the type tests individually.
