### ISSUE TITLE
Secure contexts only?

### ISSUE THREAD

**Issue by inexorabletash** [domenic/async-local-storage#16]
While Indexed DB is usable in non-secure contexts, we are likely to offer new native storage APIs only in secure contexts since storage is a "powerful feature". We followed that path for SW's Cache API. 

This might be predicated on whether we expose the layered web API concept in all contexts. If that's already been decided in favor of restricting, then this is implicitly resolved. Otherwise... could go either way IMHO.

**Comment by domenic** [comment]
I think this should be restricted, as a new way to store persistent data. I added a step that makes importing this module in non-secure contexts throw. Alternately we could make any usage of a StorageArea in a non-secure context throw, but this seemed to make more sense at least to me.
