### ISSUE TITLE
Implementing clear() via database deletion?

### ISSUE THREAD

**Issue by domenic** [domenic/async-local-storage#17]
I was thinking it'd be a nice way to address #8 and part of #13 by having clear() delete the database entirely. I'm not sure the best IDB-ese for how to do this. From what I gather from the spec, you need to close the database before deleting it.

So far I have two ideas:

- Call database.close(), then when that request succeeds, call indexedDB.deleteDatabase()
- In the upgradeneeded event for the database, check for cases where the version is transitioning to null, and close the database in that case.
  - This also handles deletion through raw IDB API usage, which is a nice bonus.

Thoughts, @inexorabletash?

**Comment by inexorabletash** [comment]
> Call database.close(), then when that request succeeds, call indexedDB.deleteDatabase()

`close()` doesn't return anything you can wait on, but that's fine. You can issue the close and then the delete and the delete will get queued until the close (and any others ) succeeds.

Otherwise, SGTM.

(Uh oh... this means domenic is really internalizing IDB. He's gonna be dangerous now...)
