### ISSUE TITLE
backingStore API might not be quite right

### ISSUE THREAD

**Issue by domenic** [domenic/async-local-storage#23]
It occurs to me you can't really use the IndexedDB database manually, once a StorageArea has opened it. (Unless we add explicit `close()`; see #13.)

As such, the only way to really use `backingStore` is:

```js
const backingStoreInfo = (new StorageArea("foo")).backingStore;
```

But this is kind of awkward, creating a StorageArea with no intention of actually using it. Instead, maybe it should just be

```js
const backingStoreInfo = StorageArea.backingStore("foo");
```

**Comment by domenic** [comment]
Wait, no, this is wrong, you can totally have multiple open connections to the same database at once. There's no problem here.

/cc @jsbell to double-check me.

**Comment by inexorabletash** [comment]
Confirmed. No problem here.
