### ISSUE TITLE
Questions re: isolated (or shared) areas

### ISSUE THREAD

**Issue by brettz9** [domenic/async-local-storage#26]
Hi,

Looks great...

I have a couple questions:

1. The spec proposal mentions in two non-normative sections that `StorageArea` works for isolated storage areas, but I'm wondering whether the normative section ought to mention how this scoping works (if it doesn't already and I'm just missing something). How is scoped beyond existing `localStorage` restrictions?
2. Could some means be provided to allow a special storage area that requires user permission but which is shared across all domains? I am very eager to see site-agnostic storage mechanisms (ideally for IndexedDB too) so that, as on the desktop, the user's data created by one application need not be privileged over others (though obviously under user control). (This could I think be polyfilled in some manner as a third-party script as a go-between for asking and granting permission, even allowing namespacing and chaining multiple domains together to avoid storage size restrictions, but there'd be the issue of trust of the 3rd party.)

**Comment by domenic** [comment]
For 1, the normative sections do spell out how this works, although I can see how tracing it through might be a bit difficult. See for example https://domenic.github.io/async-local-storage/#initialize-the-database-promise, which opens a database based on the [[DatabaseName]] set in the constructor.

For 2, I think that's out of scope for now, but might be a good future API. Especially if we can prove out how to build it in JavaScript as a library, the layered API constraints make it especially easy to then add to the platform.

**Comment by brettz9** [comment]
FWIW, I've made a humble repo which aims to demonstrate and polyfill the `SharedStorage` proposal.

The demo at https://brettz9.github.io/SharedStorage/test/ shows the ability to work cross-domain (albeit with unpkg.com via `postMessage` instead of the browser), storing cross-domain accessible storage on the unpkg  "server", a site which for now fulfills the role of what the browser would do.

The last tests are particularly relevant as they use the proposed Promise-based API rather than directly using the lower level `postMessage` communications on which the polyfill is based and which the tests also check. (And if you see a failure in a `getMaxRemaining` test, that is not an issue.)

I'd be most appreciative of any feedback or guidance on possible next steps...
