### ISSUE TITLE
class StorageArea JS definition marks delete as a keyword

### ISSUE THREAD

**Issue by kenchris** [domenic/async-local-storage#27]
Subject says it all (SSIA)

**Comment by kenchris** [comment]
s/keyboard/keyword :-) More coffee needed!

**Comment by domenic** [comment]
Yeah, this is a limitation of the Pygments syntax highlighter, and doesn't have any normative effect on the spec. Not much we can do, although filing a bug on Pygments would be appreciated.

**Comment by kenchris** [comment]
Is `delete` a better name that `remove`?
