### ISSUE TITLE
Expose the methods off async-local-storage as separate exports

### ISSUE THREAD

**Issue by SanderElias** [domenic/async-local-storage#29]
I think it would help developers if you would expose the methods of the storage class also.

that way I could do something like this:
```
import {set as save, get as load} from "...."
```
perhaps even rename/provide aliases from the get go.
I would like to see `save|load|list|remove`.

I know the last thing is a very bikeshedding sensitive one, sorry ;)

**Comment by domenic** [comment]
I think this breaks the model of `storage` being an instance of the `StorageArea` class, for little gain. So, let's avoid this.

You can still do

```js
const { set: save, get: load } = storage;
```

if you want.
