### ISSUE TITLE
Should undefined be special-cased to mean not-present?

### ISSUE THREAD

**Issue by domenic** [domenic/async-local-storage#3]
Right now the API distinguishes between "not present" and "has undefined", in the same way that JS maps do.

localStorage only allows string values, so passing undefined is the same as passing "undefined".

localForage seems to convert undefined to null, but then store it anyway.

The alternative is to say that setting an item to undefined (and null?) is equivalent to deleting it. So any values set to undefined would be deleted from the keys/values/entries, in particular.

If we did this, we could also get rid of the has() method, which does not exist in localStorage, and encourages error-prone racy code like

```js
if (await als.has("key")) {
  const val = await als.get("key");
  // oops, val might have been deleted between the has and the get; the has didn't buy us anything
}
```

instead encouraging people to do

```js
const val = await als.get("key");
if (val !== undefined) {
  // good to go
}
```

Note that this issue becomes moot if we resolve #2 in favor of restricting values to strings.

**Comment by jakearchibald** [comment]
I was leaning towards allowing `undefined` and not-existing to be different things, as with maps & arrays, but the `has` example is pretty compelling.

Yeah, maybe it's better to treat `undefined` as unsetting.

**Comment by inexorabletash** [comment]
FWIW, this is indeed considered a minor footgun with raw IndexedDB; you can't distinguish not-existing an `undefined` via the `get()` API, and must use cursors or `count()`.

**Comment by domenic** [comment]
@inexorabletash do you have any takes on how best to avoid that footgun here? It seems like since we're operating at a high-level, we have the tools to go either way:

- Have has() be implemented in terms of count(); it works just like an ES Map
- Have set(x, undefined) actually do a delete under the hood; there is no observable difference
  - Optionally have values()/keys()/entries() filter out entries with undefined values, although those could only get there via raw IDB manipulation

**Comment by inexorabletash** [comment]
I don't have useful instincts here. I'd prefer Map-like API (allowing `undefined` as a value and offering `has()`) but I'm not a typical user.

**Comment by domenic** [comment]
What use cases would you have for distinguishing, even if you're not a typical user?

**Comment by inexorabletash** [comment]
I know there's overhead in shipping a value back and deserializing, so I'd use `has()` for existence checks. And I'd be unlikely to store a raw `undefined` as a value. Library authors that wrap APIs like Indexed DB may be more concerned about such edge cases as they aren't in control of what data the library is asked to store. What does localForage do here?

I asked an engineer sitting next to me (totally unbiased sample...) for an opinion, hopefully in a not leading way: he thought a failed `get()` would obviously reject rather than resolve to undefined, acknowledging that's different than what either Map or localStorage does.

**Comment by domenic** [comment]
> I know there's overhead in shipping a value back and deserializing, so I'd use has() for existence checks. 

But, what kind of code would use existence checks, but not then subsequently get the value in the error-prone fashion of the OP? That's the part I'm missing.

> What does localForage do here?

localForage converts undefined to null, and then stores the null. I'm not sure why. I think it might be a side effect of some JSON serializing?

**Comment by inexorabletash** [comment]
> But, what kind of code would use existence checks, but not then subsequently get the value...

Flags. Not the most exciting answer, but present/not present is easier than the tri-state of not-present/present-but-false/present-but-true.

**Comment by domenic** [comment]
Marking as "tentatively resolved" in favor of keeping has()/get() separate and treating undefined/not present as different. But, open to persuasion.

**Comment by pwnall** [comment]
Unpopular opinion: setting to `undefined` returns a rejected promise, and `undefined` can be used reliably to detect absence.

I recognize this is a trade-off, and there are legitimate cases for storing `undefined`. I'm just saying those will be traded off (the API can still accept `[undefined]`) for the benefit of being able to do a read that also indicates whether the key existed or not.

My motivation is that I've had to check whether a cache contains an item or not a lot more often than I've had to store `undefined`. You might tell me that I can easily get what I want with the current API, as long as I never store `undefined`. In that case, I'd respond that all it takes is one bug that writes `undefined` to persistent storage, and I'm stuck doing `has` / `get` for my app's lifetime.

By the way, the bug above is why I want a throw on `undefined`. I'd prefer an error to silent data loss.

**Comment by Krinkle** [comment]
I agree with @pwnall that we should try hard to avoid an API with silent failures.

If we don't want to support storing `undefined`, then `set()` should refuse to do so - not doing a `delete()` instead.
If we do want to support calling `set('key', undefined)` without rejection, then it should also result in `get('key')` resolving, to `undefined`. And arguably it should also result in `has()` returning true. If there is desire for a shortcut that rejects stored `undefined`, perhaps `has()` could check both existence and not `undefined`, but that'd probably surprise/confuse users.

**Comment by domenic** [comment]
> If we do want to support calling set('key', undefined) without rejection, then it should also result in get('key') resolving, to undefined. And arguably it should also result in has() returning true.

That is the current design. I think from a JS API perspective that makes the most sense, as it matches the Map API, as well as the normal JS object model (i.e. `x[y] = undefined; x[y] === undefined; y in x === true`).

I think there's an alternate API which treats API as a no-value, where setting something to `undefined` effectively deletes it. In that model, we get rid of `has()` entirely, and you use `await storage.get(x) === undefined` to check for existence/nonexistence, which has some benefits in avoiding [race conditions](https://domenic.github.io/async-local-storage/#example-has-race-conditions). I don't think this counts as "silent data loss": you set something to `undefined`, and you get back `undefined` when retrieving it.

So in summary the proposals on the table are:

#### Undefined as a first-class value (current proposal)

```js
await storage.get(neverSetKey) === undefined;
await storage.has(neverSetKey) === false;

await storage.set(x, undefined);
await storage.get(x) === undefined;
await storage.has(x) === true;

await storage.delete(x);
await storage.get(x) === undefined;
await storage.has(x) === false;
```

_Note: all these statements have exact analogies with JS `Map`s or objects._

### Undefined ~ not present

```js
await storage.get(neverSetKey) === undefined;
// storage.has does not exist

await storage.set(x, undefined);
await storage.get(x) === undefined;
// storage.has does not exist

await storage.delete(x); // sugar for `await storage.set(x, undefined)
await storage.get(x) === undefined;
// storage.has does not exist
```

### Undefined rejects (by @pwnall)

```js
await storage.get(neverSetKey) === undefined;
await storage.has(neverSetKey) === false;

try { await storage.set(x, undefined); } catch {} // throws
await storage.get(x) === undefined;               // x was never set
await storage.has(x) === false;                   // x was never set

await storage.delete(x);            // no-op
await storage.get(x) === undefined; // x was never set
await storage.has(x) === false;     // x was never set
```

_Note: it seems like this would also be amenable to a variant where has() does not exist._

Of these I am torn between "undefined as a first class value" and "undefined ~ not present". I'm not sure I see many benefits to "undefined rejects".

**Comment by domenic** [comment]
We will not use exceptions for non-exceptional situations, such as getting a value that was never set.

**Comment by benitogf** [comment]
agree to disagree that `getting a value that was never set` is exceptional :man_shrugging:
