### ISSUE TITLE
Make all methods on async-local-storage curried

### ISSUE THREAD

**Issue by SanderElias** [domenic/async-local-storage#30]
I would love to see that the methods exposed support currying.
In this case, I think a sample tell more as I could ever describe in words.

```
import {storage} from ...
export const saveUser = strorage.set('user')
export const loadUser = storage.get('user')
```

This will be very useful for all the methods that are in there that need more as 1 parameter. and allows for a more functional style of programming.

**Comment by domenic** [comment]
Since we don't do this anywhere else on the platform, I don't think it's appropriate to start with this specification, sorry.
