### ISSUE TITLE
build in import will fail if not secure origin, but it sounds like that is not the case for polyfill

### ISSUE THREAD

**Issue by kenchris** [domenic/async-local-storage#32]
> If the built-in implementation is not imported in a secure context, the import statement will cause a "SecurityError" DOMException, as persistent storage is a powerful feature.

Is that the case? I think any import including a build-in (existing or not) module should always fail if not in a secure context

**Comment by kenchris** [comment]
It sounds like that might already be the case:

> The layered API’s evaluation steps are the following:
> If the current settings object is not contextually secure, throw a "SecurityError" DOMException.

But then the above could be clarified

**Comment by domenic** [comment]
> I think any import including a build-in (existing or not) module should always fail if not in a secure context

Why?

We've added a secure context restriction for async local storage, as you noted, because it's a powerful feature (access to storage). I'd be open to adding it to all LAPIs, but politically restricting non-powerful features has been challenging.

**Comment by kenchris** [comment]
It seems weird to me that because I am on HTTP, it will fail to load the native impl, but may load the polyfill instead (even if that might fail if indexedDB or other feature being polyfilled, requires secure origin)

**Comment by domenic** [comment]
Well, if it were a faithful polyfill that implemented the evaluation steps, the polyfill would fail to load too. If it's not a faithful polyfill, then I imagine there's lots of potential for mismatch, of which this is just one...

**Comment by kenchris** [comment]
Yes, I understand how you handle this now. It is up to the polyfill to follow the spec requirements around secure origin. I still think it might make sense to clarify

**Comment by domenic** [comment]
What kind of note, in what location, would you expect?

**Comment by kenchris** [comment]
Maybe below

> If the built-in implementation is not imported in a secure context, the import statement will cause a "SecurityError" DOMException, as persistent storage is a powerful feature.

NOTE: Import statements importing layered APIs don't require secure origin, including for eventual polyfills. The polyfill for this feature thus need to cause a "SecurityError" DOMException as well, in order to compliantly polyfill this feature.

(feel free to write in a more proper way)

I think that the "build-in" is what confused me as it makes it sound like it won't apply to a polyfill.
