### ISSUE TITLE
Is it OK to use a Map-like API surface, instead of a localStorage-like one?

### ISSUE THREAD

**Issue by domenic** [domenic/async-local-storage#4]
In particular, the decision to align with Map aligns with recent web platform APIs such as the Cache API, Headers, URLSearchParams, etc. (Although some of those are multimaps, so they have slightly bigger APIs.)

But, does this modernization detract from the "it's just local storage, but better" story?

**Comment by jakearchibald** [comment]
idb-keyval uses `get`/`set` rather than `getItem`/`setItem`. No one's complained.

**Comment by domenic** [comment]
Marking as "tentatively resolved" in favor of the current Map-esque naming choices.

**Comment by domenic** [comment]
Closing as I have become pretty sure this is the right choice.
