### ISSUE TITLE
Incomplete specification for database creation

### ISSUE THREAD

**Issue by pwnall** [domenic/async-local-storage#42]
IIUC, https://domenic.github.io/async-local-storage/#initialize-the-database-promise essentially states that the `versionchange` handler for the database open request is `(event) => event.result.close()`. I think the handler needs to create the sole object store used by the DB.

**Comment by domenic** [comment]
Does the `upgradeneeded` handler in step 7 not suffice? It seems to in practice, but the event dance here was pretty complicated...

**Comment by pwnall** [comment]
Oh, sorry, I got confused. The spec is fine as is.
