### ISSUE TITLE
Add methods to encourage atomic operations?

### ISSUE THREAD

**Issue by domenic** [domenic/async-local-storage#5]
This is definitely beyond the scope of "local storage, but better". But, should we add methods that encourage patterns that aren't as prone to interleaving?

To be concrete, we're worried about patterns such as

```js
if (!(await als.has("key")) {
  await als.set("key", "value");
  // oops, someone in another tab might have set something in between has returning and set being called
}
```

Methods that could help with this are

- setIfAbsent()
- Making set return the value that was present before the change (or adding a new method that does this)
- replaceAll() = clear() + a series of sets
- Versions of set/delete that operate on multiple entries at once

Alternately, we could encourage using [web locks](https://github.com/inexorabletash/web-locks/) in conjunction?

Or, we could add "lightweight" transactions!?! Eek.

My tendency is thinking that this is too much scope creep, and that if you need these kind of atomicity guarantees, IDB with its full-fledged transactions support is your best bet. But I'd love to hear more.

**Comment by jakearchibald** [comment]
> My tendency is thinking that this is too much scope creep, and that if you need these kind of atomicity guarantees, IDB with its full-fledged transactions support is your best bet

Agreed. There could be a little helper like:

```js
const [idbTransaction, idbObjectStore] = await storage.transaction('readwrite');
```

Which saves you the trouble of opening the DB, and getting the correct store, but for the actual actions you're in IDB land now.

**Comment by jakearchibald** [comment]
The downside to the above is you're using raw IDB. `backingStore` makes it easier to use stuff like https://www.npmjs.com/package/idb, so maybe that's better.

**Comment by domenic** [comment]
I'm pretty sure we're not going to do this, so let me close this issue.
