### ISSUE TITLE
What if the database is broken?

### ISSUE THREAD

**Issue by jakearchibald** [domenic/async-local-storage#8]
If I, or some stupid 3rd party of, run code like:

```js
indexedDB.open('async-local-stroage', 15);
```

Am I now locked out of `async-local-storage` for life? Will it try to defend against this, or simply throw?

**Comment by jakearchibald** [comment]
Throwing is probably the best that can be done here.

**Comment by inexorabletash** [comment]
If we go with one-database-per-area (see https://github.com/domenic/async-local-storage/issues/10), we could engineer `clear()` to work around this by turning it into a database delete/open. It would block if any connections at a higher version are open, but would reset the version.

This complicates the definitions of the other methods, and may be surprising. In conjunction with [lazy-open](https://github.com/domenic/async-local-storage/issues/15), maybe it's not so bad, though.
